### ISSUE TITLE
Bad file number during android socket read .. struggling in this exception please help

### ISSUE THREAD

**Issue by pradeeppareek** [readium/readium-sdk#210]
java.net.SocketException: recvfrom failed: EBADF (Bad file number)
            at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:552)
            at libcore.io.IoBridge.recvfrom(IoBridge.java:516)
            at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
            at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
            at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
            at okio.Okio$2.read(Okio.java:139)
            at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
            at okio.RealBufferedSource.read(RealBufferedSource.java:50)
            at com.squareup.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:464)
            at okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
            at java.io.InputStream.read(InputStream.java:163)

**Comment by rkwright** [comment]
Can you provide a little more context?  Which version of the OS?  Device? Does this happen with all books or just some or a particular book?  Any additional details would be helpful.
